networks:
  ags-core:
    name: ags-core
    driver: bridge

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: keycloak-mssql-db
    ports:
      - "1433:1433"
    # hostname: ags-mssql # 127.0.0.1 this is host name incase we need to connect to the database from the host machine
    user: root 
    environment:
      - ACCEPT_EULA=Y # https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-configure?view=sql-server-ver15&pivots=cs1-bash#persist
      - MSSQL_SA_PASSWORD=P@ssw0rd # https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&tabs=cli&pivots=cs1-bash#run-the-container-2
      - MSSQL_PID=Developer
    volumes:      
      - ./mssql/data:/var/opt/mssql/data # https://stackoverflow.com/questions/65307784/mssql-container-fails-to-start-when-mapping-volumes-after-upgrading-to-wsl2
      - ./mssql/log:/var/opt/mssql/log
      - ./mssql/secrets:/var/opt/mssql/secrets
    networks:
      - ags-core

  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    container_name: keycloak-mssql-tools
    depends_on:
      - mssql
    command: /bin/bash -c 'if /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "P@ssw0rd" -Q "SELECT COUNT(*) FROM sys.databases WHERE name = N''Keycloak''" | grep -q "0"; then /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "P@ssw0rd" -Q "create database Keycloak"; fi; /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "P@ssw0rd" -Q "use master; EXEC sp_sqljdbc_xa_install;"'
    networks:
      - ags-core

  keycloak:
    image: ${REGISTRY:-ags}/keycloak:${TAG:-latest}
    container_name: keycloak
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: 
    - start
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KC_HTTP_RELATIVE_PATH: /
      KC_DB: mssql
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: P@ssw0rd
      KC_DB_SCHEMA: dbo
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: P@ssw0rd
      KC_DB_URL_HOST: 127.0.0.1
      KC_DB_URL_PORT: 1433
      KC_DB_URL_DATABASE: "auth"
      KC_DB_URL: 'jdbc:sqlserver://mssql:1433;databaseName=auth;encrypt=false;trustServerCertificate=true;loginTimeout=30;'
      KC_TRANSACTION_XA_ENABLED: false
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: 'edge'
      KC_LOG_LEVEL: INFO
    depends_on:
      - mssql
      - mssqlscripts
    networks:
      - ags-core