# Project configuration for Serena
# See: https://oraios.github.io/serena/02-usage/050_configuration.html

project_name: "fastmicro"

# Python (primary) for all microservices and shared library.
# TypeScript for the webshell-service (Next.js/React frontend).
languages:
- python
- typescript

# the encoding used by text files in the project
# For a list of possible encodings, see https://docs.python.org/3.11/library/codecs.html#standard-encodings
encoding: "utf-8"

# whether to use project's .gitignore files to ignore files
ignore_all_files_in_gitignore: true

# Additional paths to ignore (gitignore syntax)
ignored_paths:
- "**/__pycache__"
- "**/.venv"
- "**/.env"
- "**/node_modules"
- "**/.next"
- "**/*.egg-info"
- "**/dist"
- "**/build"
- "**/.mypy_cache"
- "**/.pytest_cache"
- "**/.ruff_cache"
- "**/.coverage"
- "**/htmlcov"
- ".serena/cache"
- "infrastructure/postgres"
- "k6"

# whether the project is in read-only mode
# If set to true, all editing tools will be disabled and attempts to use them will result in an error
# Added on 2025-04-18
read_only: false

# list of tool names to exclude. We recommend not excluding any tools, see the readme for more details.
# Below is the complete list of tools for convenience.
# To make sure you have the latest list of tools, and to view their descriptions, 
# execute `uv run scripts/print_tool_overview.py`.
#
#  * `activate_project`: Activates a project by name.
#  * `check_onboarding_performed`: Checks whether project onboarding was already performed.
#  * `create_text_file`: Creates/overwrites a file in the project directory.
#  * `delete_lines`: Deletes a range of lines within a file.
#  * `delete_memory`: Deletes a memory from Serena's project-specific memory store.
#  * `execute_shell_command`: Executes a shell command.
#  * `find_referencing_code_snippets`: Finds code snippets in which the symbol at the given location is referenced.
#  * `find_referencing_symbols`: Finds symbols that reference the symbol at the given location (optionally filtered by type).
#  * `find_symbol`: Performs a global (or local) search for symbols with/containing a given name/substring (optionally filtered by type).
#  * `get_current_config`: Prints the current configuration of the agent, including the active and available projects, tools, contexts, and modes.
#  * `get_symbols_overview`: Gets an overview of the top-level symbols defined in a given file.
#  * `initial_instructions`: Gets the initial instructions for the current project.
#     Should only be used in settings where the system prompt cannot be set,
#     e.g. in clients you have no control over, like Claude Desktop.
#  * `insert_after_symbol`: Inserts content after the end of the definition of a given symbol.
#  * `insert_at_line`: Inserts content at a given line in a file.
#  * `insert_before_symbol`: Inserts content before the beginning of the definition of a given symbol.
#  * `list_dir`: Lists files and directories in the given directory (optionally with recursion).
#  * `list_memories`: Lists memories in Serena's project-specific memory store.
#  * `onboarding`: Performs onboarding (identifying the project structure and essential tasks, e.g. for testing or building).
#  * `prepare_for_new_conversation`: Provides instructions for preparing for a new conversation (in order to continue with the necessary context).
#  * `read_file`: Reads a file within the project directory.
#  * `read_memory`: Reads the memory with the given name from Serena's project-specific memory store.
#  * `remove_project`: Removes a project from the Serena configuration.
#  * `replace_lines`: Replaces a range of lines within a file with new content.
#  * `replace_symbol_body`: Replaces the full definition of a symbol.
#  * `restart_language_server`: Restarts the language server, may be necessary when edits not through Serena happen.
#  * `search_for_pattern`: Performs a search for a pattern in the project.
#  * `summarize_changes`: Provides instructions for summarizing the changes made to the codebase.
#  * `switch_modes`: Activates modes by providing a list of their names
#  * `think_about_collected_information`: Thinking tool for pondering the completeness of collected information.
#  * `think_about_task_adherence`: Thinking tool for determining whether the agent is still on track with the current task.
#  * `think_about_whether_you_are_done`: Thinking tool for determining whether the task is truly completed.
#  * `write_memory`: Writes a named memory (for future reference) to Serena's project-specific memory store.
excluded_tools: []

# list of tools to include that would otherwise be disabled (particularly optional tools that are disabled by default)
included_optional_tools: []

# fixed set of tools to use as the base tool set (if non-empty), replacing Serena's default set of tools.
# This cannot be combined with non-empty excluded_tools or included_optional_tools.
fixed_tools: []

# base_modes are always active regardless of CLI parameters
base_modes:

# Default modes: interactive + editing + planning
default_modes:
- interactive
- editing
- planning

# initial prompt for the project. It will always be given to the LLM upon activating the project
# (contrary to the memories, which are loaded on demand).
initial_prompt: |
  # FastMicro — Enterprise Python Microservices Platform

  ## Overview
  FastMicro is a production-ready, enterprise-grade Python microservices monorepo using FastAPI,
  modern tooling, and cloud-native best practices. Python >=3.12, package manager: uv, build system: hatchling.

  ## Technology Stack
  | Layer         | Technology                              |
  |---------------|-----------------------------------------|
  | Frontend      | Next.js 15, React 19, TypeScript        |
  | API Gateway   | Traefik 3.x                             |
  | Backend       | FastAPI, Python 3.12+                   |
  | Auth          | Keycloak 24+ (external IdP)             |
  | Databases     | PostgreSQL 17, MongoDB 7                |
  | Caching       | Redis 8                                 |
  | Messaging     | RabbitMQ 4                              |
  | Secrets       | HashiCorp Vault                         |
  | Metrics       | Prometheus + Grafana                    |
  | Logging       | Seq (structured JSON), structlog        |
  | Tracing       | Jaeger via OpenTelemetry                |
  | CI/CD         | GitHub Actions                          |

  ## Repository Structure
  ```
  /                          -- monorepo root
  ├── shared/                -- enterprise shared library (cross-cutting concerns)
  ├── services/
  │   ├── audit-service/     -- centralized audit logging (port 8001)
  │   ├── identity-service/  -- OAuth 2.0 / OIDC identity provider
  │   ├── identity-admin-service/ -- internal admin UI for IdP (port 8081)
  │   ├── metastore-service/ -- metadata & feature flags (port 8002)
  │   └── webshell-service/  -- Next.js frontend (port 3000)
  ├── gateways/
  │   └── federation-gateway/ -- central OIDC auth gateway (port 8000)
  ├── infrastructure/        -- Helm charts, Terraform, monitoring, scripts
  ├── docs/                  -- architecture docs, ADRs
  └── docker-compose.yml     -- local orchestration
  ```

  ## Architecture (ADR-001: Clean Architecture)
  All Python services follow Clean Architecture with 4 layers (dependencies flow inward):
  - API layer (api/): FastAPI routers, DTOs, request/response models
  - Application layer (application/): Services, use cases, orchestration
  - Domain layer (domain/): Entities, value objects, repository interfaces, domain events
  - Infrastructure layer (infrastructure/): Database repos, external integrations, caching

  ## Shared Library (ADR-002) — shared/
  Enterprise shared library with 16 modules providing cross-cutting concerns:

  | Module              | Purpose                                                    |
  |---------------------|------------------------------------------------------------|
  | application/        | BaseService, BaseReadService, BaseWriteService, CRUDService, ServiceContext |
  | auth/               | API key validation, JWT utilities, password hashing        |
  | cache/              | CacheBackend protocol, decorators, distributed locking, Redis |
  | config/             | Pydantic Settings for app, auth, DB, caching, logging, Redis, security |
  | constants/          | Environment detection, HTTP status codes, regex patterns   |
  | dbs/                | AbstractRepository, InMemoryRepository, AbstractUnitOfWork, Filter, PageRequest/PageResponse |
  | ddd/                | Entity, AggregateRoot, EntityId, DomainEvent, EventDispatcher, ValueObject |
  | exceptions/         | BaseServiceException, HTTP exceptions (400-504), DB/validation exceptions |
  | extensions/         | retry, cache, rate_limit, timeout decorators; DI Container |
  | fastapi_utils/      | Exception handlers, health routers, lifespan, middleware   |
  | http_client/        | Circuit breaker, resilient HTTP client                     |
  | observability/      | Structured logging, Prometheus metrics, OpenTelemetry tracing, health checks |
  | proto/              | Protobuf definitions (placeholder)                        |
  | sqlalchemy_async/   | Async SQLAlchemy session management, base models, AsyncRepository/AsyncCRUDRepository |
  | utils/              | UTC datetime helpers, JSON serialization, string utils, validators |

  ## Services Detail
  - audit-service: Centralized audit logging for GDPR/SOC2/HIPAA compliance. FastAPI + SQLAlchemy async + asyncpg.
  - identity-service: Enterprise IdP — OAuth 2.0 Authorization Code + PKCE, Client Credentials, JWT (RS256), MFA (TOTP). FastAPI + Authlib.
  - identity-admin-service: Internal-only admin UI for IdP management. FastAPI + Jinja2. Security: VPN, IP whitelist, MFA.
  - metastore-service: Metadata management with key-value store, feature flags, versioning. FastAPI + DDD.
  - webshell-service: Web frontend. Next.js 15, React 19, TypeScript, Radix UI, TanStack Query/Table, react-hook-form, zod, next-auth.
  - federation-gateway: Central OIDC auth gateway. FastAPI + httpx + authlib.

  ## Key Patterns
  - Repository Pattern: AbstractRepository -> AsyncCRUDRepository (SQLAlchemy) or InMemoryRepository (tests)
  - Unit of Work: AbstractUnitOfWork with async context manager (commit/rollback)
  - DDD Building Blocks: Entity, AggregateRoot, EntityId, ValueObject, DomainEvent/EventDispatcher
  - CQRS-light: BaseReadService / BaseWriteService separation
  - Dependency Injection: FastAPI Depends() with Annotated types; custom DI Container in shared.extensions
  - Resilience: Circuit Breaker (CLOSED/OPEN/HALF_OPEN), retry with backoff, timeout, rate limiting, bulkhead
  - Configuration: Pydantic BaseSettings with env vars, @lru_cache for singleton (avoid unhashable args!)
  - Observability (ADR-003): structlog JSON logging, OpenTelemetry tracing with @traced, Prometheus metrics with @timed
  - Health Checks: /health/live (liveness) + /health/ready (readiness) with component checks

  ## Coding Conventions
  - Linter: ruff (rules: A, E, W, F, I, B, C4, UP, SIM, PTH, RUF), line-length=100
  - Type checker: mypy strict mode with pydantic plugin
  - Formatter: ruff format (double quotes, spaces)
  - Naming: snake_case (functions/variables), PascalCase (classes), UPPER_CASE (constants)
  - Async: ALL I/O operations must be async
  - API versioning: /api/v1/ prefix on all routes
  - Type hints: Required on all function signatures, use Annotated for DI
  - Docstrings: PEP 257, required for public classes/functions

  ## Testing Conventions
  - Framework: pytest >=8.0, pytest-asyncio (asyncio_mode = "auto"), pytest-cov, pytest-mock
  - Structure: tests/unit/, tests/integration/, tests/e2e/ per service
  - Markers: @pytest.mark.unit, @pytest.mark.integration, @pytest.mark.slow
  - Coverage: >=80% threshold, branch coverage enabled
  - Patterns: AsyncMock for repos/services, InMemoryRepository for unit tests, aiosqlite for async DB tests
  - Frontend: Vitest + Testing Library (unit), Playwright (e2e), MSW (API mocking)

  ## Known Anti-Patterns to AVOID
  - datetime.utcnow() -> use datetime.now(timezone.utc) instead
  - @lru_cache on functions with unhashable args (e.g., dicts) -> causes TypeError
  - Hardcoded file paths -> use pathlib.Path relative to __file__
  - Manual service instantiation -> use DI Container or FastAPI Depends()
  - SELECT * in queries -> select only needed columns
  - Synchronous I/O in async context -> always use async variants

  ## Key File Locations
  - Shared library source: shared/src/shared/
  - Shared library tests: shared/tests/
  - Service source pattern: services/<name>/src/<name_underscore>/
  - Architecture docs: docs/architecture.md
  - ADRs: docs/adr/
  - Docker orchestration: docker-compose.yml
  - Helm chart: infrastructure/charts/microservice/
  - Instruction files: .github/instructions/ (python, enterprise patterns, cloud-native, observability, security)
# override of the corresponding setting in serena_config.yml, see the documentation there.
# If null or missing, the value from the global config is used.
symbol_info_budget:

# The language backend to use for this project.
# If not set, the global setting from serena_config.yml is used.
# Valid values: LSP, JetBrains
# Note: the backend is fixed at startup. If a project with a different backend
# is activated post-init, an error will be returned.
language_backend:
